#!/bin/bash

export TARGETDIR=$(pwd)/target
export LOGDIR=$(pwd)/logs
export APPJAR=$TARGETDIR/app.jar

mkdir $TARGETDIR || true
mkdir $LOGDIR || true

makejar() {
echo "Building Spring Petclinic into $APPJAR"
docker buildx bake --progress plain --load -f bake.hcl jar

export SRCJAR=/home/myapp/spring-petclinic-main/target/spring-petclinic-3.0.0-SNAPSHOT.jar
docker run --rm --entrypoint cat petclinic-builder:v1 $SRCJAR > $APPJAR
echo "Building JAR [DONE]"
}

maketools() {
echo "Building Benchmark Tools"
docker buildx bake --progress plain --load -f bake.hcl tools
echo "Building Benchmark Tools [DONE]"
}

makeenv() {
export CONFIG=$1
docker buildx bake --progress plain --load -f bake.hcl $CONFIG
docker buildx bake --progress plain --load -f bake.hcl $CONFIG
}

if [ "$1" = "custom" ]; then
    if [ -f "$APPJAR" ]; then
        echo "The script will use your custom app ($FILE)"
    else
        echo "The script must use your custom app ($FILE), but it doesn't exist"
        exit
   fi
else
  makejar
fi


maketools

makeenv "alpaquita"
makeenv "official"
makeenv "semeru"
makeenv "temurin"