#!/bin/bash

export TARGETDIR=$(pwd)/target
export LOGDIR=$(pwd)/logs
export APPJAR=$TARGETDIR/app.jar

mkdir $TARGETDIR || true
mkdir $LOGDIR || true

maketest() {
export CONFIG=$1
echo "Running benchmarks for $CONFIG"
docker rm petclinic-benchmark-$CONFIG
docker run --memory=2g --mount type=bind,source="$(pwd)"/benchmark.sh,target=/home/myapp/benchmark.sh --name petclinic-benchmark-$CONFIG petclinic-benchmark-$CONFIG:v1

echo "Making copy of logs into $LOGDIR"
mkdir $LOGDIR || true
docker cp petclinic-benchmark-$CONFIG:/home/myapp/log $LOGDIR/$CONFIG-log || true
echo "Benchmarks for $CONFIG [DONE]"
}

makeplots() {
export PYTHON_PARAMS="$@"

echo "Creating plots for for $PYTHON_PARAMS"
docker rm tools-python
docker run \
--mount type=bind,source="$(pwd)"/plots.py,target=/home/myapp/plots.py \
--mount type=bind,source="$(pwd)"/logs,target=/home/myapp/logs \
--name tools-python \
tools-python:v1 python \
/home/myapp/plots.py $PYTHON_PARAMS


echo "Making copy of logs into $LOGDIR"
mkdir $LOGDIR || true
docker cp tools-python:/home/myapp/plot/. $LOGDIR || true
echo "Plots for $PYTHON_PARAMS [DONE]"
}

maketest "alpaquita"
maketest "official"
maketest "semeru"
maketest "temurin"

makeplots alpaquita,official,semeru,temurin

echo "DONE"
