FROM bellsoft/liberica-runtime-container:jdk-17-stream-musl
WORKDIR /home/myapp
RUN apk add curl unzip
# The last commit before migration to Spring Boot 3 and Java 17
RUN curl -L https://github.com/spring-projects/spring-petclinic/archive/6e71aaa44cbd147a000d3a7b4bd5db55244948bf.zip --output spring-petclinic-main.zip
RUN unzip ./spring-petclinic-main.zip
RUN mv /home/myapp/spring-petclinic-6e71aaa44cbd147a000d3a7b4bd5db55244948bf /home/myapp/spring-petclinic-main
RUN cd /home/myapp/spring-petclinic-main && ./mvnw dependency:resolve
RUN rm -rf /home/myapp/repo