FROM dist-base
WORKDIR /home/myapp
RUN apk update
RUN apk add abuild build-base git curl openssl openssl-dev zlib-dev bash
RUN apk add python3 python3-dev
RUN python -m ensurepip --upgrade
RUN pip3 install --upgrade pip
RUN pip3 install psrecord
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install matplotlib
